sandbox:
  driver_instance_pool_id: 'xxxx'
  instance_pool_id: 'xxxx'
  policy_id: 'xxxx'
  spn_id: 'xxxx'
  timeout_seconds: 7200
  warning_threshold_seconds: 3600
  cluster_tags:
    sub_team: Home
    resource_Type: etl-jobs
  permissions:
      can_manage: group:admins
      can_manage_run: user:foo@bar.com, user:user@org.com
      can_view: user:view_user@org.com


prod:
  driver_instance_pool_id: 'xxxx'
  instance_pool_id: 'xxxx'
  policy_id: 'xxxx'
  notebook_path: 'xxxx'
  spn_id: 'xxxx'
  cluster_tags:
    sub_team: Home
    resource_Type: etl-jobs
  timeout_seconds: 7200
  warning_threshold_seconds: 3600
  custom_tags:
    sub_team: Home
    resource_Type: etl-jobs
  permissions:
    can_manage: group:admins
    can_manage_run: user:foo@bar.com, user:user@org.com
    can_view: user:view_user@org.com

jobs:
  - job_name: jb_incr_ing_<group_name_from_config>
    email_notification_list: sample_email@org.com
    notebook_path: '<notebook_path_in_workspace>'
    spark_conf:
      spark.driver.extraJavaOptions: "-Duser.timezone=Asia/Kolkata"
      spark.executor.extraJavaOptions: "-Duser.timezone=Asia/Kolkata"
    schedule: "10 30 8 * * ?"
    job_parameters:
      base_checkpoint_path: 'abfss://container@sa.dfs.core.windows.net/ingestion_checkpoints'
      group_name: <group_name_from_config>
  
  - job_name: jb_incr_ing_<group_name_from_config>
    email_notification_list: sample_email@org.com, sample2@org.com
    notebook_path: '/Workspace/Shared/path/to/notebook'
    spark_conf: null
    schedule: "10 30 8 * * ?"
    timeout_seconds: 21600
    warning_threshold_seconds: 7200
    max_concurrent_runs: 1
    job_parameters: null
    is_queue_enabled: false
    pause_schedule: false
    tags:
      developer_name: "user"
      job_type: "incremental_ingestion"

  
  
    
  
    


